name: Generate Combined Markdown

# 2025-08-22 Friday 18:02:50.  JMH test numero uno.  2025-08-22 Friday 18:15:03.  Signed into GH.
# Trigger when files are pushed to the docs folder
on:
  push:
    paths:
      - 'docs/**'
    branches:
      - main
  # Also allow manual triggering for testing
  workflow_dispatch:

jobs:
  generate-md:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: Run your MD generator script
    - name: Generate combined markdown
      run: |
        echo "Running MD generator..."
        python src/md_generator.py
        echo "MD generation complete!"

    # Step 5: Check what files were created/modified
    - name: Show generated files
      run: |
        echo "Files in repository after generation:"
        ls -la
        echo "Git status:"
        git status

    # Step 6: Commit and push any generated files back to repo
    - name: Commit generated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-generated combined markdown files"
          git push
        fi
